const GET_ALL_CASES = 'GET_ALL_CASES';
const OPEN_CASE = 'OPEN_CASE';
const REFRESH_FILE_LIST = 'REFRESH_FILE_LIST';
const CREATE_GRAPH = 'CREATE_GRAPH';
const UPDATE_GRAPH = 'UPDATE_GRAPH';
const SET_PARENT_AND_CHILD_NODES = 'SET_PARENT_AND_CHILD_NODES';
const SET_ROUTE = 'SET_ROUTE';
const SIDE_DISPLAY = 'SIDE_DISPLAY';

export {GET_ALL_CASES, OPEN_CASE, REFRESH_FILE_LIST, CREATE_GRAPH, UPDATE_GRAPH, SET_PARENT_AND_CHILD_NODES, SET_ROUTE, SIDE_DISPLAY}
