const GET_ALL_CASES = 'GET_ALL_CASES';
const OPEN_CASE = 'OPEN_CASE';
const REFRESH_FILE_LIST = 'REFRESH_FILE_LIST';
const CREATE_GRAPH = 'CREATE_GRAPH';
const UPDATE_GRAPH = 'UPDATE_GRAPH';

export {GET_ALL_CASES, OPEN_CASE, REFRESH_FILE_LIST, CREATE_GRAPH, UPDATE_GRAPH}
